### PR TITLE
0.4.39 h0fb591

### LINKED ISSUE #2: windows failed initial commit
This is blocking libmediainfo and pymediainfo first commit builds.

### PR DESCRIPTION
**Pull request by anjos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR closes #2, closes #3 and closes #4 at once!

### CODE REVIEW

**Comment by anjos** [comment]
@sodre, this can now be merged.  It brings the latest libzen 0.4.39 into conda-forge, together with Windows support as well.

**Comment by anjos** [comment]
@conda-forge/staged-recipes is there an ad hoc reviewer that could check this and #6 ?

**Comment by anjos** [comment]
@conda-forge-admin, please ping team

**Comment by mariusvniekerk** [comment]
I'd advise you add yourself as a maintainer on this feedstock

**Pull request merged**
